BASE = ../../rai

#uncomment this and comment the line below to use with CMake build of rai
RAI_CMAKE = 1
#DEPEND = Core Geo Kin Gui Control KOMO Optim

OBJS = main.o myspace.o mycontrollers.o

include $(BASE)/build/generic.mk

